RADIO = float (input("INGRESA EL RADIO DEL CIRCULO:"))
ALTURA = float (input("INGRSA LA ALTURA DEL CIRCULO:"))
VOLUMEN = 3.141592 * (RADIO ** 2) * ALTURA
ARE = 2 * 3.141592 * RADIO * ALTURA
print(f"UN CIRCULO CON RADIO {RADIO} Y UNA ALTURA DE {ALTURA} SU VOLUMEN ES {ARE} Y SU AREA ES DE  {ARE}")

