B = float (input("INGRESA LA BASE DEL TRIANGULO:"))
A = float (input("INGRSA LA ALTURA DEL TRIANGULO:"))
RES = (B * A) / 2
print(f"UN TRIANGULO CON BASE: {B} MTS Y ALTURA: {A} MTS, SU PERIMETRO ES DE: {RES} MTS")
