#HERNANDEZ SANCHEZ ULISES
CAL = float (input("INGRESA LA CALIFICACIÓN DEL ALUMNO:"))
if CAL > 5 :
 print(f"EL ALUMNO SACO {CAL} APROBADO")
 print("FIN DEL PROGRAMA")
if CAL < 6 :
 print(f"EL ALUMNO SACO {CAL} REPROBADO")
 print("FIN DEL PROGRAMA")
