print(f"ESTE PROGRAMA SIRVE PARA QUE EL USUARIO PUEDA SABER CUANTOS LITROS DE GASOLINA PAGARA")
GAL = float(input("INGRESA EL NUMERO DE GALONES DE GASOLINA:"))
TOTAL = GAL * 3.785 *8.20
print(f"EL NUMERO DE GALONES INGRESADOS SON: {GAL}. EL PRECIO QUE DEBERA PAGAR EL CLIENTE ES DE:${TOTAL}$")
