NOM = str (input("INGRESA EL NOMBRE DEL DINOSAURIO:"))
PES = float (input("INGRESA EL PESO DEL DINOSAURIO :"))
LONG = float (input ("INGRESA LA LONGITUD DEL DINOSAURIO:"))
PESKIL = PES * 1000 #LI PESO EN LIBRAS
LONGMET = LONG * 0.3047 #LP LONGITUD EN PIES
print(f"UN DINOSAURIO CON NOMBRE: {NOM} CON PESO: {PES} Y LONGITUD {LONG} /n/n TIENE UN PESO DE:{PESKIL} KILOS Y UNA LONG DE: {LONGMET} MTRS ")
